name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install modules
        run: npm install
      - name: Run unit tests
        run: npm run test
      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage/clover.xml, ./coverage/coverage-final.json, ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
